/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function greet(a: number, b: number): void;
export function __wbg_parameters_free(a: number): void;
export function __wbg_swarm_free(a: number): void;
export function swarm_tick(a: number): void;
export function swarm_new(a: number, b: number): number;
export function swarm_width(a: number): number;
export function swarm_height(a: number): number;
export function swarm_number_boids(a: number): number;
export function swarm_x(a: number): number;
export function swarm_y(a: number): number;
export function swarm_dx(a: number): number;
export function swarm_dy(a: number): number;
export function swarm_set_width(a: number, b: number): void;
export function swarm_set_height(a: number, b: number): void;
export function swarm_set_border(a: number, b: number): void;
export function swarm_set_separation_min_distance(a: number, b: number): void;
export function swarm_set_cohesion(a: number, b: number): void;
export function swarm_set_separation(a: number, b: number): void;
export function swarm_set_alignment(a: number, b: number): void;
export function swarm_set_visual_range(a: number, b: number): void;
export function swarm_set_speed_limit(a: number, b: number): void;
export function swarm_set_mouse_interactivity(a: number, b: number): void;
export function swarm_set_follow_fear(a: number, b: number): void;
export function swarm_set_mouse_position(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_exn_store(a: number): void;
